### ISSUE TITLE
Markdown versions of basic rules

### ISSUE THREAD

**Issue by ptbannister** [EliAndrewC/l7r#2]

**Comment by ptbannister** [comment]
@EliAndrewC since you've accepted the first set of files, I'll do the others too.

This raises the specter of having to make changes in two places, which all developers hate and try to avoid. So that leads to the question, what do you want to do long term with the Open Document Format versions?

Now that we play on Discord, I personally like having Markdown versions of these files that I can open in a separate browser tab during sessions. I like that better than viewing them in Open Office - I prefer switching browser tabs instead of switching application windows.

On the other hand, I got feedback from one of our other players that he prefers having them in a separate application window instead of switching browser tabs.

I don't have a strong opinion on what should happen to the ODF files, I'm just happy to have files in a version I can view in my browser.

**Comment by EliAndrewC** [comment]
Actually I'm already most of the way through making these conversions myself, so no worries about that, thanks!

Honestly, it was all of the schools that made me feel like the task was overwhelming and caused me to keep putting this off, so I'm super grateful for that.

**Comment by EliAndrewC** [comment]
W.r.t. the odt files I'm inclined to just delete them from the repo.  Git maintains the commit history so we can go back and retrieve them if we ever want/need to.  Unless one of the players indicates that they really prefer the office format, in which case we can figure out what to do next... even in that case I'd be inclined to do some kind of automatic conversion which keeps the md files as the canonical source and makes the open office documents autogenerated based on that.

**Comment by EliAndrewC** [comment]
I've pushed new versions of the files at
https://github.com/EliAndrewC/l7r/tree/master/rules

Thanks again!  I'm going to close this issue now as resolved, though eventually I should add some additional files for things which are currently only in the wiki, like the Mass Combat rules, the Between Place rules, the Spirit Encounter rules, lobbying rules, etc.
